### ISSUE TITLE
feeds displayed from oldest to newest

### ISSUE THREAD

**Issue by kobolibra** [diffbot/rss-anything#3]
hi hi, thank you for this. It came to me the feeds are extracted with the oldest on top while the newest to the bottom. How can i have the newest on top? Thank you.

**Comment by jeromechoo** [comment]
@kobolibra could you share the generated feed? A lot of RSS readers will sort it automatically for you too.

**Comment by kobolibra** [comment]
> @kobolibra could you share the generated feed? A lot of RSS readers will sort it automatically for you too.

Thank you for the prompt response. Take below as an example. My RSS reader will only be able to take 5 feeds, that means all of those 5 will be the oldest if there are more than 5 feeds. Maybe this will be an issue only for the first time I subscribe. Once subscribed any future updates will still be able to come in I hope.

**https://www.sequoiacap.com/stories/**

**Comment by jeromechoo** [comment]
Apologies for the late reply I was sick for the past week. 

This page doesn't supply a published date for any of the listed posts. So posts will appear in the RSS feed in the order they are shown on the page.

**Comment by kobolibra** [comment]
> Apologies for the late reply I was sick for the past week.
> 
> This page doesn't supply a published date for any of the listed posts. So posts will appear in the RSS feed in the order they are shown on the page.

Thank you jerome for your reply. That helps.

Stay safe and stay healthy!

**Comment by kobolibra** [comment]
@jeromechoo 

hello hello, I am afraid I still feel confused here. This url https://www.sequoiacap.com/stories/?_story-category=perspective

each article has its own publish date, the 1st one "The AI Supply Chain Tug of War" is the latest. But it is displayed to the very bottom of the RSS feeds (https://rss.diffbot.com/rss?url=https://www.sequoiacap.com/stories/?_story-category%3Dperspective). So the order in the website is different from the order in the feeds. 

I believe the issue is with the pub date though that might be an issue as well. I assume RSS-anything is crawling topdown, so the 1st item on the web is extracted and added into feed list, and the 2nd is extracted and added in the list, on top of the 1st item, and on and on. This means the items on top of a website will always get to be on the bottom of the feed list. In other words, the latest on a website (most of the time will be on top of a website) ended up on the bottom of the feed list. That is RSS-Anything will always reverse the order of the original items. Does that mean the pub date should be readily available on the main page (for example https://www.sequoiacap.com/stories/?_story-category=perspective) instead of on the separate pages of each of the item, for this to work? Is it possible to change the order how the items are stored in the feeds? Normally i would assume what is on the top is the latest. 

Thank you and have a great day.

**Comment by jeromechoo** [comment]
@kobolibra 

This is fixed. In a situation where none of the posts have dates it will sort the feed in the same order as the page.

> Does that mean the pub date should be readily available on the main page (for example https://www.sequoiacap.com/stories/?_story-category=perspective) instead of on the separate pages of each of the item, for this to work?

Yes. If RSS Anything extracted every page on the list it would take forever to load the feed.

**Comment by kobolibra** [comment]
> @kobolibra
> 
> [This is fixed](https://github.com/diffbot/rss-anything/commit/7b251f8ee048c4a51d3e61c2235e4e557289fe7f). In a situation where none of the posts have dates it will sort the feed in the same order as the page.
> 
> > Does that mean the pub date should be readily available on the main page (for example https://www.sequoiacap.com/stories/?_story-category=perspective) instead of on the separate pages of each of the item, for this to work?
> 
> Yes. If RSS Anything extracted every page on the list it would take forever to load the feed.

Thank you Jerome. A great day ahead.
